### ISSUE TITLE
Not able to add header element.

### ISSUE THREAD

**Issue by sanfern** [mosn/proxy-wasm-go-host#13]
I am trying to add a header element to the request _OnHttpRequestHeaders_. It's not working or an error. Sample call - `proxywasm.AddHttpRequestHeader("Debug", "1")`, After this call context return back to the caller no instruction are executed.

**Comment by sanfern** [comment]
@antJack Thanks for your response. Not working, I added following code in the example.
```// override.
func (im *importHandler) AddHttpRequestHeader(key, value string) error {
	im.reqHeader.Add(key, value)
	return nil
}
```

**Comment by Taction** [comment]
@sanfern I've run into a similar situation. Because the abi standard has not been fully documented, there is still a little difference between this project and the implementation of envoy. Especially if your wasm plugin works with the envoy, your wasm will not be loaded correctly unless you have added/modified some functions.
